apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-dep
  namespace: devops-python
spec:
  replicas: 3
  selector:
    matchLabels:   
      app: python-app
  template:
    metadata:
      labels:       
        app: python-app
    spec:
      containers:
        - name: python-app
          image: mohdahmad12870/devops-python-app:1.0
          ports:
            - containerPort: 5000

