kind: Pod
apiVersion: v1
metadata:
  name: python-app-pod
  namespace: devops-python
  labels:
    app: python-app
spec:
  containers:
    - name: python-app
      image: mohdahmad12870/devops-python-app:1.0
      ports: 
      - containerPort: 5000   
